name: Publish releases for IDeSyDe

on:
  release:
    types: [created]

jobs:
  publish-java-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Set up JDK 
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "graalvm-ce-java11@21.1.0"
    - name: Get scala version
      id: get_scala_version
      run: |
        cd ${{ github.workspace }}
        echo "::set-output name=scalaVersion::$(sbt --error 'print cli / scalaVersion')"
    - name: Build assembly with sbt
      run: |
        cd ${{ github.workspace }}
        sbt assembly
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/scala-cli/target/scala-${{ steps.get_scala_version.outputs.scalaVersion }}/cli-assembly-${{ steps.get_version.outputs.version-without-v }}.jar
        asset_name: idesyde-${{ steps.get_version.outputs.version-without-v }}-standalone.jar
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable IDeSyDe standalone jar"
  publish-windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Set up JDK 
      uses: olafurpg/setup-scala@v11
      with:
    - name: Build assembly with sbt
      run: |
        cd ${{ github.workspace }}
        sbt "Universal / packageBin"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/scala-cli/target/universal/cli-${{ steps.get_version.outputs.version-without-v }}.zip
        asset_name: idesyde-${{ steps.get_version.outputs.version-without-v }}-windows.zip
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable IDeSyDe standalone EXE"
  publish-linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Set up JDK 
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "amazon-corretto@1.11.0-11.9.1"
    - name: Build assembly with sbt
      run: |
        cd ${{ github.workspace }}
        sbt "Universal / packageBin"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/scala-cli/target/universal/cli-${{ steps.get_version.outputs.version-without-v }}.zip
        asset_name: idesyde-${{ steps.get_version.outputs.version-without-v }}-linux.zip
        tag: "${{ github.ref }}"
        overwrite: true
        body: "Executable IDeSyDe standalone linux ZIP"
